### ISSUE TITLE
Feedback UML Gewächshaus

### ISSUE THREAD

**Issue by LexQzim** [xqly-stack/java#10]
Moin Oleg, 

es freut mich zu sehen, wie du das UML gelöst hast und größtenteils hast du auch alles drin, was in der Aufgabenstellung angegeben war. 
Kurze Frage vorab: Mit was hast du das UML Diagramm erstellt? 

Ich gehe bei meinem Feedback zu erst auf die Dinge ein, welche fehlen und dann auf die Dinge, welche du zusätzlich gemacht hast. 

### Was fehlt noch?
- Die Subklassen Hydrokultur, Kakteen und Stauden fehlen
- Es fehlt die Möglichkeit, dass eine Pflanze einem Pflegesystem zugewiesen werden kann. OK, also bei dir werden die Pflanzen über den Konstruktor zugewiesen. Ist ok. Lass ich gelten. 
Alternativ hätte ich hier auch eine extra Methode akzeptiert
- Deine Pflegesysteme lassen sich nicht aktivieren und deaktieren. Da hätte ich mir eine einfache Methode gewünscht. Oder meinst du damit die Methode wasser() und lampe() 
    - Wenn ja, dann sind diese Methode leider nicht gut benannt. Methodennamen müssen selbstsprechend sein und stellen eine Aktion da. Also verwende hier bitte immer ein Verb. 

### Was hast du extra gemacht? 
- toString() war nicht gefordert, aber ist auch nicht falsch
- Ich verstehe die Methode lampe(), wasser(), zustandPflanze() nicht. Wie schon gesagt. VErwende mehr Verben
- Was ist getSZustand()?
- Was ist li_sys und bw_sys? Sei nicht zu faul deine Varibalen vernünftig auszuschreiben. Dein Editor macht für dich die Vervollständigung und wenn du später sehr große Programme hast, dann wird es mit solchen Abkürzungen unübersichtlich. Oder stell dir mal vor ein neuer Kollege soll deinen Quellcode weiter bearbeiten und dieser Kollege kommt aus Frankreich. Wie soll dieser deine Abkürzungen interpretieren? Ausgeschrieben kann man es ja noch übersetzen, aber so wird es sehr schwer deinen Quellcode nachzuvollziehen. 
- Das Ändern vom Zustand war nicht gefordert. Also incrementWZustand() und incrementSZustand(). Versuch bitte in diesen Aufgaben erstmal nur das Minimum zu erzeugen. Anschließend darfst du dieser gerne erweitern und mit als extra abgeben. Nur die Erweiterung zu sehen, dass fällt mir schwer zu Bewerten. Es ist einfacher, wenn du mir die gefoderter Minimalversion gibst und dann noch wo du Potential drin siehst. Dann kann ich dir dafür mehr Credits geben. (Außer in der Abschlussprüfung. Da ist es stark reglementiert. Konzentriere dich da erstmal nur auf die Minimallösung, auch wenn es dir schwer fällt)

Ansonsten soweit gut und ich finde es auch sehr gut von dir, dass du das Programm auch richtig entwicklet hast. Sehr cool

**Comment by xqly-stack** [comment]
Das UML Diagramm wurde mit Draw.io erstellt und auf diese Repo exportiert

**Comment by LexQzim** [comment]
Top.
Sieht ansonsten echt gut aus.
